### ISSUE TITLE
Feature request: Add "shared goods"

### ISSUE THREAD

**Issue by PottiMc** [Marmo/debitum#108]
For example, I ordered a tent together with two friends. Everybody paid the same amount.

I want to keep track where it is staying at the moment. So technically it is not a debt.

Would be nice to have "shared" stuff tracked.

**Comment by Marmo** [comment]
Hi @PottiMc , thanks for your suggestion. I thought about it, and while I understand that this feature would be quite useful, I feel it is beyond the scope of debitum, at least at the moment.
