### ISSUE TITLE
When I repaid money pressing the three dots in the initial transaction, the app crash.

### ISSUE THREAD

**Issue by sdgrs546547Q** [Marmo/debitum#111]
Steps to reproduce
1. Open Debitum
2. Go to "money" section
3. Long press the inicial transaction
4. Press the three dots and press the repaid button
5. App crash.

My device is a Poco X3 pro. It has Android 12.
Language: Spanish
Date format: dd-mm-yy

Thanks

**Comment by Marmo** [comment]
🙁 Thanks for reporting. Can confirm this and will look into it.
