### ISSUE TITLE
Pressing the "+" button in the things ("Dinge") screen crashes the app

### ISSUE THREAD

**Issue by TuringTux** [Marmo/debitum#118]
The error occurs in Debitum version 1.7.0.

After pressing "+" in the things screen, the app immediately closes and android shows its "App was closed repeatedly" message. This does not happen in any other screen.

If you need more details to reproduce the error, I'll gladly be of assistance.

**Comment by Marmo** [comment]
Thanks for reporting. This is probably related to #111 and fixed in 1.7.1, which should be available in F-Droid in the next few days.

**Comment by TuringTux** [comment]
Thank you for the great app and the swift reply! I will re-check with 1.7.1 :)
