### ISSUE TITLE
wrong calculation !

### ISSUE THREAD

**Issue by mateus1619** [Marmo/debitum#129]
![IMG-20230812-WA0000.jpg](https://github.com/Marmo/debitum/assets/83937109/3f43e3aa-c688-4039-8798-5ccaf9983364)

There's something wrong with my total debts

**Comment by Marmo** [comment]
What would you expect to see as the total debt? Debitum does 65+76-100+2=43 which seems correct to me.

**Comment by mateus1619** [comment]
> What would you expect to see as the total debt? Debitum does 65+76-100+2=43 which seems correct to me.

Got it!  I was confused and thanks for the explanation.
