### ISSUE TITLE
Hide Soft-Keyboard when clicking somewhere in EditTransaction Dialog

### ISSUE THREAD

**Issue by Marmo** [Marmo/debitum#14]
Suggestion by @mezysinc from #9:
Hide the soft keyboard when clicking somewhere in the one of the edit dialogs. This would be especially useful in the editTransaction dialog as some inputs are hidden behind the keyboard, yet the content cannot be scrolled upwards. So the user currently has to hide the keyboard using the system-back-button, which is kind of inconvenient.

An alternative would be to make the content scrollable.

Related by @mezysinc in #25 
> I'd be good to automatically scroll up input box (with text) that is hidden behind keyboard (to be able to see what's being written there). After swiping away keyboard it should automatically scroll down to where it was (related to #14)

**Comment by mezysinc** [comment]
> You are running 1.2.2, right? Cannot reproduce it, maybe I do not understand what you mean. Can you please add a step by step description what you are doing and what goes wrong in a new issue? thx!

![Debitum_1_1](https://user-images.githubusercontent.com/81477718/122624216-879e9480-d075-11eb-96f1-1bfe12648475.png)
![Debitum_2_1](https://user-images.githubusercontent.com/81477718/122624219-89685800-d075-11eb-9388-331ae37c8bbb.png)
![Debitum_3_1](https://user-images.githubusercontent.com/81477718/122624221-8a00ee80-d075-11eb-8e4d-f8e7ea33b153.png)

**Comment by Marmo** [comment]
let's continue this in #28

**Comment by Marmo** [comment]
The dialog's contents is now scrollable so that every input field can be accessed easily. If you feel this needs improvement, feel free to comment/reopen!
