### ISSUE TITLE
Add other date formats

### ISSUE THREAD

**Issue by roshavagarga** [Marmo/debitum#17]
Pretty self-explanatory, I'd like to have YY/MM/DD and DD/MM/YY as options :)

**Comment by Marmo** [comment]
Thanks for your suggestion! I'll put that on my TODO, but do not know when I have time to implement that.

**Comment by roshavagarga** [comment]
@Marmo This, as well as all of the other suggestions are just that - suggestions. Don't feel inclined to add them to the TODO or prioritize them in any way if you feel they don't agree with your design philosophy for the app :)

**Comment by Marmo** [comment]
Of course :) But the date formats are something I was thinking about anyway, but have rather low prio to me.
