### ISSUE TITLE
Add item photos

### ISSUE THREAD

**Issue by roshavagarga** [Marmo/debitum#21]
Example: You give a tool to Jerry, snap a photo or series of photos, it gets filed with the item. Jerry returns the tool X months later, you compare it to the photos and see if there's been any damage in the meantime.

**Comment by Marmo** [comment]
That could be quite useful I think. Probably will implement this one day ;)

**Comment by Marmo** [comment]
Implemented with 9d529eb53101ec1e9ee64267cdccb1db11aa75a2
Yay! Now add your photos ;)
