### ISSUE TITLE
Add ACRA support

### ISSUE THREAD

**Issue by roshavagarga** [Marmo/debitum#22]
In case you want to have crash reports in an open source way, this library is a good option that's accepted by F-Droid. Should be disabled by default for the user though :)

**Comment by Marmo** [comment]
need to have a look into this and decide if I really want this.

**Comment by Marmo** [comment]
Thinking about this I came to the conclusion, that getting crash reports would
1. create too much effort for me that I am not willing to invest into this project (Debitum)
2. Force me to add internet permission which I want to avoid

Thus I will not add ACRA (or any other crash reporting solution) to Debitum.
