### ISSUE TITLE
Add charge(s) & transaction method

### ISSUE THREAD

**Issue by roshavagarga** [Marmo/debitum#23]
Transaction method is self-explanatory - you might have loaned the money in cash, through a bank transfer or through something else. This is useful to keep track of why you might have made any transactions, especially if it's a joint account and your memory isn't the best.

Charges are any charges you had to pay along the way - Samantha wanted 1000 in cash, you had to withdraw the money and got a 10 dollar charge to do that, had to drive to and from her town which was another 30 in gas, etc.

**Comment by Marmo** [comment]
Again: Thanks for sharing your ideas with me!

Also here I'd like to keep things simple, so:

> Transaction method is self-explanatory - you might have loaned the money in cash, through a bank transfer or through something else. This is useful to keep track of why you might have made any transactions, especially if it's a joint account and your memory isn't the best.

I would propose to use the description field for that (where it matters one can note the transaction method).

> Charges are any charges you had to pay along the way - Samantha wanted 1000 in cash, you had to withdraw the money and got a 10 dollar charge to do that, had to drive to and from her town which was another 30 in gas, etc.

You could either edit the original transaction and add the additional 10+30 dollars, using the description how the $1040 are composed or add separate transactions (one for $10 bank charge, one for $30 gas) again using the description to clarify why you want that back from Samantha.

I understand that if always or nearly always these special things had to be noted, dedicated fields would be preferrable, but this is not the use case I intend the app to be used for, so I do not plan to implement this.
