### ISSUE TITLE
Update pt-br F-Droid full_description

### ISSUE THREAD

**Issue by Marmo** [Marmo/debitum#25]
@mezysinc 
I added a note about the app's scope (and non-scope) to Readme and the descriptions for F-Droid. Could you take a look at 
[full_description.txt](../blob/master/fastlane/metadata/android/pt-BR/full_description.txt) and translate the yet-english new paragraph there?
Thanks in advance!

**Comment by mezysinc** [comment]
Some new inconsistencies ;

- Whatever date you set it always falls down by '-1', let's say you set it to 10.05 it goes to 09.05

- disallow returned date to be set before the date of actual transaction


- I'd be good to automatically scroll up input box (with text) that is hidden behind keyboard (to be able to see what's being written there). After swiping away keyboard it should automatically scroll down to where it was (related to #14)

**Comment by Marmo** [comment]
Closed by #26

**Comment by mezysinc** [comment]
@Marmo take a look at message above

...some new inconsistencies

**Comment by Marmo** [comment]
ah, thx, was already searching for this ^^

> disallow returned date to be set before the date of actual transaction

Created #27 for this, but not sure if and when I will implement it

> Whatever date you set it always falls down by '-1', let's say you set it to 10.05 it goes to 09.05

You are running 1.2.2, right? Cannot reproduce it, maybe I do not understand what you mean. Can you please add a step by step description what you are doing and what goes wrong in a new issue? thx!

> I'd be good to automatically scroll up input box (with text) that is hidden behind keyboard (to be able to see what's being written there). After swiping away keyboard it should automatically scroll down to where it was (related to #14)

Added it as a note to #14

**Comment by mezysinc** [comment]
https://github.com/Marmo/debitum/issues/14#issuecomment-864320877, sorry I pasted it in 14, take a look over there

**Comment by mezysinc** [comment]
Too many tabs opened, bad habit

**Comment by Marmo** [comment]
No problem, moved it to a new one (#28 )
