### ISSUE TITLE
Date decreased by 1 day after finishing Date Picker

### ISSUE THREAD

**Issue by Marmo** [Marmo/debitum#28]
_Originally posted by @mezysinc in https://github.com/Marmo/debitum/issues/14#issuecomment-864320877_

![Debitum_1_1](https://user-images.githubusercontent.com/81477718/122624216-879e9480-d075-11eb-96f1-1bfe12648475.png)
![Debitum_2_1](https://user-images.githubusercontent.com/81477718/122624219-89685800-d075-11eb-9388-331ae37c8bbb.png)
![Debitum_3_1](https://user-images.githubusercontent.com/81477718/122624221-8a00ee80-d075-11eb-8e4d-f8e7ea33b153.png)

**Comment by Marmo** [comment]
Well that's strange. I _did_ then understand you correctly but cannot reproduce this.

I had a look into the code and the only thing I can think of is some issues relating to locale settings. Two questions:
- does decrementing the day happen in the morning and in the evening? Or does it change during the day?
- can you recall if this behaviour started happening some time or was it always present?

**Comment by Marmo** [comment]
That was the right scent :) If I set my timezone to GMT-5 I can reproduce this. 

So I will have to dig into the locale thing. Damn, hoped I could avoid this by using standard locale everywhere XD

**Comment by Marmo** [comment]
Note to self:
the problem is probably
1. I get a Date from the Date Picker that is ms from epoch in the device's locale
2. I save this Date to to the viewModel and later to the Transaction/database
3. I display it using a formatter that uses the device's locale again and interprets the Date as UTC, adjusting it using the locale's timezone.

Step 3 (timezone adjustment) should not be done as debitum does not care about locales and the Date from the database should be used as-is. So I think I should always use a GMT+0 locale upon turning the Date into a String!

**Comment by Marmo** [comment]
that seems to have fixed it. It will be release 1.3.0 that is to be released soon

**Comment by mezysinc** [comment]
great monologue ;) sorry I was busy

**Comment by mezysinc** [comment]
It works great now, well done & here I go again lol

- first idea. Wouldn't be nice to introduce another small number in entry when settling of debt is half through. Let's say I lent $1000, somebody gave back $200 (Could be positioned on the right, you could move DATE OF TRANSACTION to the left or put it in the middle) & display new subtracted amount on the right.

> ON THE RIGHT SIDE:
Default letter case:
$800 (new amount after subtraction -$200)
In smaller case below $800:
$1000 (original amount that was lent)

> That way every time someone give or get something back, you could right away know what's going on with that transaction. Every new instalment would brush away previous entry. You received $100 more and you get:

> Default letter case:
$700 (new amount after subtraction -$100)
In smaller case below $800:
$800 (previous amount after one instalment)

- second tip. & when you keep adding new entries for transactions, view stays focused on the same position & doesn't focus on newly added one

**Comment by mezysinc** [comment]
@Marmo 
I believe it would be good to change word 'GAVE' (in transaction) and replaced it with either 'RETURNED' or 'GAVE BACK' for easier understanding 

Ps. Did you read comments above?

**Comment by Marmo** [comment]
Hi @mezysinc ,
let me comment on your ideas:

### indicate returned amount in money list
since Debitum does not know about how much money was returned (return-transactions are not linked to the initial transaction, see [here](https://github.com/Marmo/debitum/issues/9#issuecomment-861314762) why), this can not be implemented

###  view stays focused on the same position & doesn't focus on newly added transaction
this was #2 and I fixed it in v1.3.1

###  I believe it would be good to change word 'GAVE' (in transaction) and replaced it with either 'RETURNED' or 'GAVE BACK' for easier understanding
You mean when using the shortcut for returning money the radio buttons should be labeled differently? Gonna think about this. The labelling then would have to depend on the direction of the initial transaction:

| initial | label RECEIVED for return txn | label GAVE for return txn |
|-----|-----|-----|
| Person gave to user | got back | (no change) |
| Person received from user | (no change) | returned / gave back |

I fear this could make it clearer for some people while leading to confusion for others. Still not sure if I will pick up this idea...

PS: feel free to open separate issues even for smaller ideas, as this makes tracking, adding them to milestones and discussing them a lot easier!
