### ISSUE TITLE
Add the option to change colors by the user

### ISSUE THREAD

**Issue by charb0nnier** [Marmo/debitum#30]
It's kind of confusing when the debt is colored green and the income is colored red. It should be reversed or at least the user should be able to change the colors by himself.

**Comment by Marmo** [comment]
Thanks for your feedback!
The idea here is that money you give away is more unconvenient (thus red) than money you get (green). The same color coding is used in the person sum list: red for money you yet have to get back (you have to be after it) and green for money you will pay back in the future (good for you to have more money than you should have).

I admit that this is a personal preference and will think about adding an option here.

**Comment by Marmo** [comment]
Note to self: add methods in Utilities to get color res int for owe/lent, read pref there and use those methods [here](https://github.com/Marmo/debitum/blob/master/app/src/main/java/org/ebur/debitum/ui/list/TransactionListViewHolder.java#L70)
