### ISSUE TITLE
Update PT-BR translation

### ISSUE THREAD

**Issue by Marmo** [Marmo/debitum#31]
Two things to be translated:

**app/src/main/res/values-pt-rBR/strings.xml**

One string to be translated is commented with
`<!-- TO BE TRANSLATED - DELETE THIS LINE WHEN DONE!-->`
(This is the default description used for settled monetary debts)

**fastlane/metadata/android/pt-BR/full_description.txt**

I added keywords to facilitate searching. I added them in English. Those **should not be touched**, but their translations added to the list, so that in the end the list consists of both English and Portuguese terms.

@mezysinc could you take a look into this? And btw thanks for all the effort you put into the pt-BR translation already!

**Comment by mezysinc** [comment]
Good to see ya again ;

>Those should not be touched

I don't know how you wanna go about it, so take it from here

>Palavras-chave: IOU (eu lhe devo), dívida, empréstimo
