### ISSUE TITLE
Crash when clicking on a person

### ISSUE THREAD

**Issue by roshavagarga** [Marmo/debitum#35]
Just that - clicking on any of the people in People crashes the app. Version is 1.3.2.

**Comment by Marmo** [comment]
Hm :( that might be related to #34 . Is it really every person? In my production installation the app crashes for all persons with notes and some of the others. #34 was some strange problem with the transition between the clicked row and the filtered money list.

**Comment by roshavagarga** [comment]
What does 'with notes' mean? I have 2 people in my list and each transaction has an attached note to it. It crashes on both of them.

**Comment by Marmo** [comment]
I mean the note you can add to the person itself (not the transaction). As far as I investigated now, the other factor that can lead to a crash is if the clicked person has all debts settled (i.e. "no debt") is shown. Is this the case with your setup (I mean do the persons have notes and/or have no debt)?

**Comment by roshavagarga** [comment]
Oh, they do have notes, I didn't remember putting those, so closing this. Will reopen if it's an issue with the next version :)
