### ISSUE TITLE
Who recived or gave?

### ISSUE THREAD

**Issue by Porrumentzio** [Marmo/debitum#5]
It was not clear to me when creating new post/entry who is the grammatical subject of the options "Received" and "Gave".
The other person or me?

**Comment by Marmo** [comment]
The idea is that the first three inputs are to be read like a sentence, like:

Porrumentzio  
Gave  
5,00  

So to explicitly answer your question: The subject is the other person (not the user).

Does that make things clearer?

**Comment by Porrumentzio** [comment]
I thought that after reading all the inputs, thanks!

Know that this order of the sentence can be impossible for some translations, so there may be problems. I say this as translator that I am. I'm closing the issue, but don't hesitate to ask whatever you want :)

**Comment by Marmo** [comment]
That came to my mind, too, when I wrote the above comment. One option would then be to use a locale-dependent layout, though I need to think further about if this raises other problems.

Can you name a language where the order "Name gave amount" would be impossible?

**Comment by Porrumentzio** [comment]
That solution would be great!
Basque (eu) for example uses another structure, and even more, some grammatical elements (cases) are marked adding ending to words; not only in Basque, but in many other languages.

Basque:
Porrumentzio-(e)k
5,00
Jaso ditu / Eman ditu

The case for Esperanto language is that it is flexible, so even if the English structure is not common in Esperanto it can be used, but marks the grammatical object.
So in Esperanto:
Porrumentzio
5,00 [unit]-(j)n
Ricevis / Donis

**Comment by Marmo** [comment]
Ok so I think I will describe this in the TRANSLATION.md file and add a specific layout as soon as someone comes up with a translation for a language with with a order that is different from English.
