### ISSUE TITLE
button to search for people

### ISSUE THREAD

**Issue by elisheny** [Marmo/debitum#52]
**Please** add a  search button in the top bar

**Comment by Marmo** [comment]
Hi @elisheny, so you would like to be able to filter the people list? Just curious: is your list really that long?

I was already thinking about some kind of search function to find transactions matching search criteria, but that would rather filter the transactions list (like "all transactions with amount > 100" or "all transactions with a description containing 'cat' ")

**Comment by elisheny** [comment]
I work in a company and my clients are about 150 people, so it is difficult for me to find them without the search button

**Comment by Marmo** [comment]
Ah ok I see. A search function makes sense then. I will implement it but don't yet know when.

**Comment by Marmo** [comment]
I decided to not implement the search function, but with the next release you will be able to sort people by name (among others). This is not equivalent to a search function, but might help.
