### ISSUE TITLE
Add option to select backup location & option for Auto backup

### ISSUE THREAD

**Issue by jerryn70** [Marmo/debitum#57]
It will be great if the app has the option to choose user defined backup location and auto backup option after adding/modifying the files

**Comment by Marmo** [comment]
I like the ideas, but still need to think of a good way to implement this from a ux perspective (e.g. will the backup be always overwritten? Can the user define, how many backups she wants to keep?).

**Comment by abda11ah** [comment]
It would be great if you could also implement the database backup on a personal cloud server.
For example through a library that allows to connect to multiple cloud servers such as rclone.

**Comment by Marmo** [comment]
> It would be great if you could also implement the database backup on a personal cloud server. For example through a library that allows to connect to multiple cloud servers such as rclone.

Hi @abda11ah thanks for your suggestion, but I do not want to add the permission to access the network to the app. So at least for now this is not an option for me.
One possibility I am thinking about is to share the backuo file es soon as it is complete so that you can choose your cloud's client app as the sharing target.

**Comment by GRFreire** [comment]
> choose [...] backup location and auto backup

That would be awesome!

Agree that adding network to such a simple app does not make sense and probably is out of scope.

I personally have a folder in my device with all my backups and that gets synced via Nextcloud. So my a simple backup in the folder of my choosing covers my use-case.

**Comment by Marmo** [comment]
Picking a backup location is implemented with 1.7.0 (see also #69); autobackup is out of scope for me as of now.

Regarding the cloud thing: If you have a cloud provider that integrates into the android file manager (like owncloud or samba shares via [Android Samba Client](https://f-droid.org/packages/com.google.android.sambadocumentsprovider/), you can also choose to write your backup there.
