### ISSUE TITLE
open backup directory from settings

### ISSUE THREAD

**Issue by nutpantz** [Marmo/debitum#69]
Newer Android versions don't allow apps to save backups anywhere, which make backups of data a nightmare to hunt all the locations of backup data.  
  
It would be nice if in the settings the app would open the directory of the backup with the users choice of file manager to copy the file where the user wants it

**Comment by rikhwanto** [comment]
Have you checked out Storage Access Framework? It's the official way to arbitrarily create and open files in storage on Android 11 and newer. I think it'll be the best approach too

**Comment by Marmo** [comment]
Closed by #101,  thanks @rikhwanto
