### ISSUE TITLE
you owe and you lent is backward on latest

### ISSUE THREAD

**Issue by nutpantz** [Marmo/debitum#70]
Under people "you owe" is displayed when you are in the green (they owe you) and "you lent" when you are in the red (you owe them)

That is backward

( Give 500 and receive 100, you are owed 400, they owe 400 to you)

**Comment by Marmo** [comment]
Hi @nutpantz, this seems like #30 to me (please read my comment there for clarification of why I chose green for money you owe them and red for money they owe you).
