### ISSUE TITLE
Disable currency decimals option/setting

### ISSUE THREAD

**Issue by Hattshire** [Marmo/debitum#71]
My country doesn't have fractions of currency, so it's kind of annoying having add 2 extra zeros every time a new transaction is added 😔

**Comment by Marmo** [comment]
Sounds reasonable. Since the amount is stored as an integer internally, this shouldn't be too hard.

**Comment by predator8bit** [comment]
+1 I was thinking of opening an issue on this exact thing, just didn't get around to doing it befor this was already here :)

**Comment by predator8bit** [comment]
I think rounding the numbers on change is fine. On the idea of a startup screen, it is fine as long as it only appears on the first startup after an update. Otherwise it would be an annoyance.

**Comment by Marmo** [comment]
Note to self: it is essential to implement #61 when releasing this, since restoring a backup in a fresh install could else cause the wrong amounts to be displayed (backed up with a setting other than 2 decimals, restoring before changing that setting from the default two of a fresh install)
