### ISSUE TITLE
Setting the Nr of decimals to a lower value breaks the input values

### ISSUE THREAD

**Issue by predator8bit** [Marmo/debitum#84]
I set the nr of decimals to 0 and when I try to add 1000 the app registers it as 100,000. Same with 1 decimal, I get 10,000.

**Comment by Marmo** [comment]
Hi @predator8bit thanks for reporting. This seems to be #79 and is fixed with 1.6.2 (already available for download from GitHub, will be on F-Droid in a few days).

**Comment by predator8bit** [comment]
Ah thanks, sorry for the duplication.
