### ISSUE TITLE
Feature request: Add language x

### ISSUE THREAD

**Issue by LordJon** [Marmo/debitum#93]
Hi there, I'd like to support this app by adding a new language. I looked at weblate, which I'm familiar with, but the language I'd like to contribute isn't there (Dutch). I expect that this is due to the requirement for it to be added in the code as well so I figured I would do a request through here.

If this isn't the right place let me know.
Btw thank you for creating this app, it's very useful!

**Comment by Marmo** [comment]
Hi, if you add Dutch to your weblate profile, you should be able to create a new language in debitum.

**Comment by LordJon** [comment]
Hi, seems I thought I was logged in but when opening my profile it gave me the login screen. Whoops, my bad. Thanks pointing this out!
